name: "Fastfetch Runner Specs"

on: 
  workflow_dispatch: # Run it manually with the 'Play' button

jobs:
  fetch-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Fastfetch
        run: |
          sudo add-apt-repository ppa:zhangsongcui3371/fastfetch -y
          sudo apt-get update
          sudo apt-get install -y fastfetch

      - name: Run Fastfetch
        run: |
          # --pipe false forces colors to show up in GitHub logs
          fastfetch --pipe false
